linters:
  enable:
    - bodyclose
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret

linters-settings:
  goimports:
    local-prefixes: github.com/yorkie-team/yorkie
  gosec:
    excludes:
      - G107  # Potential HTTP request made with variable url

issues:
  exclude-use-default: false
