linters-settings:
  goimports:
    local-prefixes: github.com/yorkie-team/yorkie

linters:
  enable:
    - bodyclose
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret

issues:
  exclude-use-default: false
