linters:
  enable:
    - errcheck
    - goimports
    - govet
    - goconst
    - gocyclo
    - gofmt
    - revive
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - wrapcheck
  disable:
    - gosimple
    - staticcheck
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/yorkie-team/yorkie
  gosec:
    excludes:
      - G107 # Potential HTTP request made with variable url
      - G115 # Ignore integer overflows
  revive:
    rules:
      - name: unused-parameter
        disabled: true
  wrapcheck:
    ignoreSigRegexps:
      - github.com/yorkie-team/yorkie # Ignore all methods in internal package
      - context.Context # Ignore all methods in context package
  gocyclo:
      min-complexity: 40

issues:
  exclude-use-default: false
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - text: "G112:"
      linters:
        - gosec
