//
// Copyright 2020 The Yorkie Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: yorkie/v1/yorkie.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientKey     string                 `protobuf:"bytes,1,opt,name=client_key,json=clientKey,proto3" json:"client_key,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateClientRequest) Reset() {
	*x = ActivateClientRequest{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateClientRequest) ProtoMessage() {}

func (x *ActivateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateClientRequest.ProtoReflect.Descriptor instead.
func (*ActivateClientRequest) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{0}
}

func (x *ActivateClientRequest) GetClientKey() string {
	if x != nil {
		return x.ClientKey
	}
	return ""
}

func (x *ActivateClientRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ActivateClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateClientResponse) Reset() {
	*x = ActivateClientResponse{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateClientResponse) ProtoMessage() {}

func (x *ActivateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateClientResponse.ProtoReflect.Descriptor instead.
func (*ActivateClientResponse) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{1}
}

func (x *ActivateClientResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type DeactivateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Synchronous   bool                   `protobuf:"varint,2,opt,name=synchronous,proto3" json:"synchronous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateClientRequest) Reset() {
	*x = DeactivateClientRequest{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateClientRequest) ProtoMessage() {}

func (x *DeactivateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateClientRequest.ProtoReflect.Descriptor instead.
func (*DeactivateClientRequest) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{2}
}

func (x *DeactivateClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *DeactivateClientRequest) GetSynchronous() bool {
	if x != nil {
		return x.Synchronous
	}
	return false
}

type DeactivateClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateClientResponse) Reset() {
	*x = DeactivateClientResponse{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateClientResponse) ProtoMessage() {}

func (x *DeactivateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateClientResponse.ProtoReflect.Descriptor instead.
func (*DeactivateClientResponse) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{3}
}

type AttachDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ChangePack    *ChangePack            `protobuf:"bytes,2,opt,name=change_pack,json=changePack,proto3" json:"change_pack,omitempty"`
	SchemaKey     string                 `protobuf:"bytes,3,opt,name=schema_key,json=schemaKey,proto3" json:"schema_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachDocumentRequest) Reset() {
	*x = AttachDocumentRequest{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDocumentRequest) ProtoMessage() {}

func (x *AttachDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDocumentRequest.ProtoReflect.Descriptor instead.
func (*AttachDocumentRequest) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{4}
}

func (x *AttachDocumentRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AttachDocumentRequest) GetChangePack() *ChangePack {
	if x != nil {
		return x.ChangePack
	}
	return nil
}

func (x *AttachDocumentRequest) GetSchemaKey() string {
	if x != nil {
		return x.SchemaKey
	}
	return ""
}

type AttachDocumentResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DocumentId         string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ChangePack         *ChangePack            `protobuf:"bytes,2,opt,name=change_pack,json=changePack,proto3" json:"change_pack,omitempty"`
	MaxSizePerDocument int32                  `protobuf:"varint,3,opt,name=max_size_per_document,json=maxSizePerDocument,proto3" json:"max_size_per_document,omitempty"`
	SchemaRules        []*Rule                `protobuf:"bytes,4,rep,name=schema_rules,json=schemaRules,proto3" json:"schema_rules,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AttachDocumentResponse) Reset() {
	*x = AttachDocumentResponse{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachDocumentResponse) ProtoMessage() {}

func (x *AttachDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachDocumentResponse.ProtoReflect.Descriptor instead.
func (*AttachDocumentResponse) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{5}
}

func (x *AttachDocumentResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *AttachDocumentResponse) GetChangePack() *ChangePack {
	if x != nil {
		return x.ChangePack
	}
	return nil
}

func (x *AttachDocumentResponse) GetMaxSizePerDocument() int32 {
	if x != nil {
		return x.MaxSizePerDocument
	}
	return 0
}

func (x *AttachDocumentResponse) GetSchemaRules() []*Rule {
	if x != nil {
		return x.SchemaRules
	}
	return nil
}

type DetachDocumentRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ClientId            string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	DocumentId          string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ChangePack          *ChangePack            `protobuf:"bytes,3,opt,name=change_pack,json=changePack,proto3" json:"change_pack,omitempty"`
	RemoveIfNotAttached bool                   `protobuf:"varint,4,opt,name=remove_if_not_attached,json=removeIfNotAttached,proto3" json:"remove_if_not_attached,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DetachDocumentRequest) Reset() {
	*x = DetachDocumentRequest{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachDocumentRequest) ProtoMessage() {}

func (x *DetachDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachDocumentRequest.ProtoReflect.Descriptor instead.
func (*DetachDocumentRequest) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{6}
}

func (x *DetachDocumentRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *DetachDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DetachDocumentRequest) GetChangePack() *ChangePack {
	if x != nil {
		return x.ChangePack
	}
	return nil
}

func (x *DetachDocumentRequest) GetRemoveIfNotAttached() bool {
	if x != nil {
		return x.RemoveIfNotAttached
	}
	return false
}

type DetachDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangePack    *ChangePack            `protobuf:"bytes,2,opt,name=change_pack,json=changePack,proto3" json:"change_pack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachDocumentResponse) Reset() {
	*x = DetachDocumentResponse{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachDocumentResponse) ProtoMessage() {}

func (x *DetachDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachDocumentResponse.ProtoReflect.Descriptor instead.
func (*DetachDocumentResponse) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{7}
}

func (x *DetachDocumentResponse) GetChangePack() *ChangePack {
	if x != nil {
		return x.ChangePack
	}
	return nil
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Resources     []*ResourceDescriptor  `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{8}
}

func (x *WatchRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *WatchRequest) GetResources() []*ResourceDescriptor {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ResourceDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Resource:
	//
	//	*ResourceDescriptor_Document
	Resource      isResourceDescriptor_Resource `protobuf_oneof:"resource"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceDescriptor) Reset() {
	*x = ResourceDescriptor{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDescriptor) ProtoMessage() {}

func (x *ResourceDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDescriptor.ProtoReflect.Descriptor instead.
func (*ResourceDescriptor) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{9}
}

func (x *ResourceDescriptor) GetResource() isResourceDescriptor_Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ResourceDescriptor) GetDocument() *DocumentDescriptor {
	if x != nil {
		if x, ok := x.Resource.(*ResourceDescriptor_Document); ok {
			return x.Document
		}
	}
	return nil
}

type isResourceDescriptor_Resource interface {
	isResourceDescriptor_Resource()
}

type ResourceDescriptor_Document struct {
	Document *DocumentDescriptor `protobuf:"bytes,1,opt,name=document,proto3,oneof"`
}

func (*ResourceDescriptor_Document) isResourceDescriptor_Resource() {}

type DocumentDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentDescriptor) Reset() {
	*x = DocumentDescriptor{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentDescriptor) ProtoMessage() {}

func (x *DocumentDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentDescriptor.ProtoReflect.Descriptor instead.
func (*DocumentDescriptor) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{10}
}

func (x *DocumentDescriptor) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type WatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*WatchResponse_Initialization
	//	*WatchResponse_Event
	Body          isWatchResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{11}
}

func (x *WatchResponse) GetBody() isWatchResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *WatchResponse) GetInitialization() *WatchInitialization {
	if x != nil {
		if x, ok := x.Body.(*WatchResponse_Initialization); ok {
			return x.Initialization
		}
	}
	return nil
}

func (x *WatchResponse) GetEvent() *WatchEvent {
	if x != nil {
		if x, ok := x.Body.(*WatchResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isWatchResponse_Body interface {
	isWatchResponse_Body()
}

type WatchResponse_Initialization struct {
	Initialization *WatchInitialization `protobuf:"bytes,1,opt,name=initialization,proto3,oneof"`
}

type WatchResponse_Event struct {
	Event *WatchEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

func (*WatchResponse_Initialization) isWatchResponse_Body() {}

func (*WatchResponse_Event) isWatchResponse_Body() {}

type WatchInitialization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceInits []*ResourceInit        `protobuf:"bytes,1,rep,name=resource_inits,json=resourceInits,proto3" json:"resource_inits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchInitialization) Reset() {
	*x = WatchInitialization{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchInitialization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchInitialization) ProtoMessage() {}

func (x *WatchInitialization) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchInitialization.ProtoReflect.Descriptor instead.
func (*WatchInitialization) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{12}
}

func (x *WatchInitialization) GetResourceInits() []*ResourceInit {
	if x != nil {
		return x.ResourceInits
	}
	return nil
}

type ResourceInit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Init:
	//
	//	*ResourceInit_DocumentInit
	Init          isResourceInit_Init `protobuf_oneof:"init"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceInit) Reset() {
	*x = ResourceInit{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInit) ProtoMessage() {}

func (x *ResourceInit) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceInit.ProtoReflect.Descriptor instead.
func (*ResourceInit) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{13}
}

func (x *ResourceInit) GetInit() isResourceInit_Init {
	if x != nil {
		return x.Init
	}
	return nil
}

func (x *ResourceInit) GetDocumentInit() *DocumentInit {
	if x != nil {
		if x, ok := x.Init.(*ResourceInit_DocumentInit); ok {
			return x.DocumentInit
		}
	}
	return nil
}

type isResourceInit_Init interface {
	isResourceInit_Init()
}

type ResourceInit_DocumentInit struct {
	DocumentInit *DocumentInit `protobuf:"bytes,1,opt,name=document_init,json=documentInit,proto3,oneof"`
}

func (*ResourceInit_DocumentInit) isResourceInit_Init() {}

type DocumentInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ClientIds     []string               `protobuf:"bytes,2,rep,name=client_ids,json=clientIds,proto3" json:"client_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentInit) Reset() {
	*x = DocumentInit{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentInit) ProtoMessage() {}

func (x *DocumentInit) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentInit.ProtoReflect.Descriptor instead.
func (*DocumentInit) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{14}
}

func (x *DocumentInit) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentInit) GetClientIds() []string {
	if x != nil {
		return x.ClientIds
	}
	return nil
}

type WatchEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*WatchEvent_DocEvent
	Event         isWatchEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{15}
}

func (x *WatchEvent) GetEvent() isWatchEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WatchEvent) GetDocEvent() *DocWatchEvent {
	if x != nil {
		if x, ok := x.Event.(*WatchEvent_DocEvent); ok {
			return x.DocEvent
		}
	}
	return nil
}

type isWatchEvent_Event interface {
	isWatchEvent_Event()
}

type WatchEvent_DocEvent struct {
	DocEvent *DocWatchEvent `protobuf:"bytes,1,opt,name=doc_event,json=docEvent,proto3,oneof"`
}

func (*WatchEvent_DocEvent) isWatchEvent_Event() {}

type DocWatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Event         *DocEvent              `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocWatchEvent) Reset() {
	*x = DocWatchEvent{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocWatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocWatchEvent) ProtoMessage() {}

func (x *DocWatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocWatchEvent.ProtoReflect.Descriptor instead.
func (*DocWatchEvent) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{16}
}

func (x *DocWatchEvent) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocWatchEvent) GetEvent() *DocEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// Deprecated: Use WatchRequest instead.
type WatchDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchDocumentRequest) Reset() {
	*x = WatchDocumentRequest{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDocumentRequest) ProtoMessage() {}

func (x *WatchDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDocumentRequest.ProtoReflect.Descriptor instead.
func (*WatchDocumentRequest) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{17}
}

func (x *WatchDocumentRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *WatchDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

// Deprecated: Use WatchResponse instead.
type WatchDocumentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*WatchDocumentResponse_Initialization_
	//	*WatchDocumentResponse_Event
	Body          isWatchDocumentResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchDocumentResponse) Reset() {
	*x = WatchDocumentResponse{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDocumentResponse) ProtoMessage() {}

func (x *WatchDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDocumentResponse.ProtoReflect.Descriptor instead.
func (*WatchDocumentResponse) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{18}
}

func (x *WatchDocumentResponse) GetBody() isWatchDocumentResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *WatchDocumentResponse) GetInitialization() *WatchDocumentResponse_Initialization {
	if x != nil {
		if x, ok := x.Body.(*WatchDocumentResponse_Initialization_); ok {
			return x.Initialization
		}
	}
	return nil
}

func (x *WatchDocumentResponse) GetEvent() *DocEvent {
	if x != nil {
		if x, ok := x.Body.(*WatchDocumentResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isWatchDocumentResponse_Body interface {
	isWatchDocumentResponse_Body()
}

type WatchDocumentResponse_Initialization_ struct {
	Initialization *WatchDocumentResponse_Initialization `protobuf:"bytes,1,opt,name=initialization,proto3,oneof"`
}

type WatchDocumentResponse_Event struct {
	Event *DocEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

func (*WatchDocumentResponse_Initialization_) isWatchDocumentResponse_Body() {}

func (*WatchDocumentResponse_Event) isWatchDocumentResponse_Body() {}

type RemoveDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ChangePack    *ChangePack            `protobuf:"bytes,3,opt,name=change_pack,json=changePack,proto3" json:"change_pack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDocumentRequest) Reset() {
	*x = RemoveDocumentRequest{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDocumentRequest) ProtoMessage() {}

func (x *RemoveDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDocumentRequest.ProtoReflect.Descriptor instead.
func (*RemoveDocumentRequest) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveDocumentRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RemoveDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RemoveDocumentRequest) GetChangePack() *ChangePack {
	if x != nil {
		return x.ChangePack
	}
	return nil
}

type RemoveDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangePack    *ChangePack            `protobuf:"bytes,1,opt,name=change_pack,json=changePack,proto3" json:"change_pack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDocumentResponse) Reset() {
	*x = RemoveDocumentResponse{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDocumentResponse) ProtoMessage() {}

func (x *RemoveDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDocumentResponse.ProtoReflect.Descriptor instead.
func (*RemoveDocumentResponse) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveDocumentResponse) GetChangePack() *ChangePack {
	if x != nil {
		return x.ChangePack
	}
	return nil
}

type PushPullChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ChangePack    *ChangePack            `protobuf:"bytes,3,opt,name=change_pack,json=changePack,proto3" json:"change_pack,omitempty"`
	PushOnly      bool                   `protobuf:"varint,4,opt,name=push_only,json=pushOnly,proto3" json:"push_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPullChangesRequest) Reset() {
	*x = PushPullChangesRequest{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPullChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPullChangesRequest) ProtoMessage() {}

func (x *PushPullChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPullChangesRequest.ProtoReflect.Descriptor instead.
func (*PushPullChangesRequest) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{21}
}

func (x *PushPullChangesRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PushPullChangesRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *PushPullChangesRequest) GetChangePack() *ChangePack {
	if x != nil {
		return x.ChangePack
	}
	return nil
}

func (x *PushPullChangesRequest) GetPushOnly() bool {
	if x != nil {
		return x.PushOnly
	}
	return false
}

type PushPullChangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangePack    *ChangePack            `protobuf:"bytes,1,opt,name=change_pack,json=changePack,proto3" json:"change_pack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPullChangesResponse) Reset() {
	*x = PushPullChangesResponse{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPullChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPullChangesResponse) ProtoMessage() {}

func (x *PushPullChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPullChangesResponse.ProtoReflect.Descriptor instead.
func (*PushPullChangesResponse) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{22}
}

func (x *PushPullChangesResponse) GetChangePack() *ChangePack {
	if x != nil {
		return x.ChangePack
	}
	return nil
}

type CreateRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRevisionRequest) Reset() {
	*x = CreateRevisionRequest{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRevisionRequest) ProtoMessage() {}

func (x *CreateRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRevisionRequest.ProtoReflect.Descriptor instead.
func (*CreateRevisionRequest) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{23}
}

func (x *CreateRevisionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateRevisionRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *CreateRevisionRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateRevisionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateRevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      *RevisionSummary       `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRevisionResponse) Reset() {
	*x = CreateRevisionResponse{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRevisionResponse) ProtoMessage() {}

func (x *CreateRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRevisionResponse.ProtoReflect.Descriptor instead.
func (*CreateRevisionResponse) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{24}
}

func (x *CreateRevisionResponse) GetRevision() *RevisionSummary {
	if x != nil {
		return x.Revision
	}
	return nil
}

type GetRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	RevisionId    string                 `protobuf:"bytes,3,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRevisionRequest) Reset() {
	*x = GetRevisionRequest{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRevisionRequest) ProtoMessage() {}

func (x *GetRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRevisionRequest.ProtoReflect.Descriptor instead.
func (*GetRevisionRequest) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{25}
}

func (x *GetRevisionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetRevisionRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GetRevisionRequest) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

type GetRevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      *RevisionSummary       `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRevisionResponse) Reset() {
	*x = GetRevisionResponse{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRevisionResponse) ProtoMessage() {}

func (x *GetRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRevisionResponse.ProtoReflect.Descriptor instead.
func (*GetRevisionResponse) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{26}
}

func (x *GetRevisionResponse) GetRevision() *RevisionSummary {
	if x != nil {
		return x.Revision
	}
	return nil
}

type ListRevisionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	IsForward     bool                   `protobuf:"varint,5,opt,name=is_forward,json=isForward,proto3" json:"is_forward,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRevisionsRequest) Reset() {
	*x = ListRevisionsRequest{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRevisionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRevisionsRequest) ProtoMessage() {}

func (x *ListRevisionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRevisionsRequest.ProtoReflect.Descriptor instead.
func (*ListRevisionsRequest) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{27}
}

func (x *ListRevisionsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ListRevisionsRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ListRevisionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRevisionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListRevisionsRequest) GetIsForward() bool {
	if x != nil {
		return x.IsForward
	}
	return false
}

type ListRevisionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revisions     []*RevisionSummary     `protobuf:"bytes,1,rep,name=revisions,proto3" json:"revisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRevisionsResponse) Reset() {
	*x = ListRevisionsResponse{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRevisionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRevisionsResponse) ProtoMessage() {}

func (x *ListRevisionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRevisionsResponse.ProtoReflect.Descriptor instead.
func (*ListRevisionsResponse) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{28}
}

func (x *ListRevisionsResponse) GetRevisions() []*RevisionSummary {
	if x != nil {
		return x.Revisions
	}
	return nil
}

type RestoreRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	RevisionId    string                 `protobuf:"bytes,4,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRevisionRequest) Reset() {
	*x = RestoreRevisionRequest{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRevisionRequest) ProtoMessage() {}

func (x *RestoreRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRevisionRequest.ProtoReflect.Descriptor instead.
func (*RestoreRevisionRequest) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{29}
}

func (x *RestoreRevisionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RestoreRevisionRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RestoreRevisionRequest) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

type RestoreRevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRevisionResponse) Reset() {
	*x = RestoreRevisionResponse{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRevisionResponse) ProtoMessage() {}

func (x *RestoreRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRevisionResponse.ProtoReflect.Descriptor instead.
func (*RestoreRevisionResponse) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{30}
}

type AttachChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ChannelKey    string                 `protobuf:"bytes,2,opt,name=channel_key,json=channelKey,proto3" json:"channel_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachChannelRequest) Reset() {
	*x = AttachChannelRequest{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachChannelRequest) ProtoMessage() {}

func (x *AttachChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachChannelRequest.ProtoReflect.Descriptor instead.
func (*AttachChannelRequest) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{31}
}

func (x *AttachChannelRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AttachChannelRequest) GetChannelKey() string {
	if x != nil {
		return x.ChannelKey
	}
	return ""
}

type AttachChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionCount  int64                  `protobuf:"varint,2,opt,name=session_count,json=sessionCount,proto3" json:"session_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachChannelResponse) Reset() {
	*x = AttachChannelResponse{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachChannelResponse) ProtoMessage() {}

func (x *AttachChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachChannelResponse.ProtoReflect.Descriptor instead.
func (*AttachChannelResponse) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{32}
}

func (x *AttachChannelResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AttachChannelResponse) GetSessionCount() int64 {
	if x != nil {
		return x.SessionCount
	}
	return 0
}

type DetachChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ChannelKey    string                 `protobuf:"bytes,2,opt,name=channel_key,json=channelKey,proto3" json:"channel_key,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachChannelRequest) Reset() {
	*x = DetachChannelRequest{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachChannelRequest) ProtoMessage() {}

func (x *DetachChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachChannelRequest.ProtoReflect.Descriptor instead.
func (*DetachChannelRequest) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{33}
}

func (x *DetachChannelRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *DetachChannelRequest) GetChannelKey() string {
	if x != nil {
		return x.ChannelKey
	}
	return ""
}

func (x *DetachChannelRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DetachChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionCount  int64                  `protobuf:"varint,1,opt,name=session_count,json=sessionCount,proto3" json:"session_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachChannelResponse) Reset() {
	*x = DetachChannelResponse{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachChannelResponse) ProtoMessage() {}

func (x *DetachChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachChannelResponse.ProtoReflect.Descriptor instead.
func (*DetachChannelResponse) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{34}
}

func (x *DetachChannelResponse) GetSessionCount() int64 {
	if x != nil {
		return x.SessionCount
	}
	return 0
}

type RefreshChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ChannelKey    string                 `protobuf:"bytes,2,opt,name=channel_key,json=channelKey,proto3" json:"channel_key,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshChannelRequest) Reset() {
	*x = RefreshChannelRequest{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshChannelRequest) ProtoMessage() {}

func (x *RefreshChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshChannelRequest.ProtoReflect.Descriptor instead.
func (*RefreshChannelRequest) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{35}
}

func (x *RefreshChannelRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RefreshChannelRequest) GetChannelKey() string {
	if x != nil {
		return x.ChannelKey
	}
	return ""
}

func (x *RefreshChannelRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RefreshChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionCount  int64                  `protobuf:"varint,1,opt,name=session_count,json=sessionCount,proto3" json:"session_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshChannelResponse) Reset() {
	*x = RefreshChannelResponse{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshChannelResponse) ProtoMessage() {}

func (x *RefreshChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshChannelResponse.ProtoReflect.Descriptor instead.
func (*RefreshChannelResponse) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{36}
}

func (x *RefreshChannelResponse) GetSessionCount() int64 {
	if x != nil {
		return x.SessionCount
	}
	return 0
}

type BroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ChannelKey    string                 `protobuf:"bytes,2,opt,name=channel_key,json=channelKey,proto3" json:"channel_key,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{37}
}

func (x *BroadcastRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *BroadcastRequest) GetChannelKey() string {
	if x != nil {
		return x.ChannelKey
	}
	return ""
}

func (x *BroadcastRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *BroadcastRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type BroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{38}
}

type WatchDocumentResponse_Initialization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientIds     []string               `protobuf:"bytes,1,rep,name=client_ids,json=clientIds,proto3" json:"client_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchDocumentResponse_Initialization) Reset() {
	*x = WatchDocumentResponse_Initialization{}
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDocumentResponse_Initialization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDocumentResponse_Initialization) ProtoMessage() {}

func (x *WatchDocumentResponse_Initialization) ProtoReflect() protoreflect.Message {
	mi := &file_yorkie_v1_yorkie_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDocumentResponse_Initialization.ProtoReflect.Descriptor instead.
func (*WatchDocumentResponse_Initialization) Descriptor() ([]byte, []int) {
	return file_yorkie_v1_yorkie_proto_rawDescGZIP(), []int{18, 0}
}

func (x *WatchDocumentResponse_Initialization) GetClientIds() []string {
	if x != nil {
		return x.ClientIds
	}
	return nil
}

var File_yorkie_v1_yorkie_proto protoreflect.FileDescriptor

const file_yorkie_v1_yorkie_proto_rawDesc = "" +
	"\n" +
	"\x16yorkie/v1/yorkie.proto\x12\tyorkie.v1\x1a\x19yorkie/v1/resources.proto\"\xbf\x01\n" +
	"\x15ActivateClientRequest\x12\x1d\n" +
	"\n" +
	"client_key\x18\x01 \x01(\tR\tclientKey\x12J\n" +
	"\bmetadata\x18\x02 \x03(\v2..yorkie.v1.ActivateClientRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x16ActivateClientResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"X\n" +
	"\x17DeactivateClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12 \n" +
	"\vsynchronous\x18\x02 \x01(\bR\vsynchronous\"\x1a\n" +
	"\x18DeactivateClientResponse\"\x8b\x01\n" +
	"\x15AttachDocumentRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x126\n" +
	"\vchange_pack\x18\x02 \x01(\v2\x15.yorkie.v1.ChangePackR\n" +
	"changePack\x12\x1d\n" +
	"\n" +
	"schema_key\x18\x03 \x01(\tR\tschemaKey\"\xd8\x01\n" +
	"\x16AttachDocumentResponse\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x126\n" +
	"\vchange_pack\x18\x02 \x01(\v2\x15.yorkie.v1.ChangePackR\n" +
	"changePack\x121\n" +
	"\x15max_size_per_document\x18\x03 \x01(\x05R\x12maxSizePerDocument\x122\n" +
	"\fschema_rules\x18\x04 \x03(\v2\x0f.yorkie.v1.RuleR\vschemaRules\"\xc2\x01\n" +
	"\x15DetachDocumentRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x126\n" +
	"\vchange_pack\x18\x03 \x01(\v2\x15.yorkie.v1.ChangePackR\n" +
	"changePack\x123\n" +
	"\x16remove_if_not_attached\x18\x04 \x01(\bR\x13removeIfNotAttached\"P\n" +
	"\x16DetachDocumentResponse\x126\n" +
	"\vchange_pack\x18\x02 \x01(\v2\x15.yorkie.v1.ChangePackR\n" +
	"changePack\"h\n" +
	"\fWatchRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12;\n" +
	"\tresources\x18\x02 \x03(\v2\x1d.yorkie.v1.ResourceDescriptorR\tresources\"]\n" +
	"\x12ResourceDescriptor\x12;\n" +
	"\bdocument\x18\x01 \x01(\v2\x1d.yorkie.v1.DocumentDescriptorH\x00R\bdocumentB\n" +
	"\n" +
	"\bresource\"5\n" +
	"\x12DocumentDescriptor\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"\x90\x01\n" +
	"\rWatchResponse\x12H\n" +
	"\x0einitialization\x18\x01 \x01(\v2\x1e.yorkie.v1.WatchInitializationH\x00R\x0einitialization\x12-\n" +
	"\x05event\x18\x02 \x01(\v2\x15.yorkie.v1.WatchEventH\x00R\x05eventB\x06\n" +
	"\x04body\"U\n" +
	"\x13WatchInitialization\x12>\n" +
	"\x0eresource_inits\x18\x01 \x03(\v2\x17.yorkie.v1.ResourceInitR\rresourceInits\"V\n" +
	"\fResourceInit\x12>\n" +
	"\rdocument_init\x18\x01 \x01(\v2\x17.yorkie.v1.DocumentInitH\x00R\fdocumentInitB\x06\n" +
	"\x04init\"N\n" +
	"\fDocumentInit\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1d\n" +
	"\n" +
	"client_ids\x18\x02 \x03(\tR\tclientIds\"N\n" +
	"\n" +
	"WatchEvent\x127\n" +
	"\tdoc_event\x18\x01 \x01(\v2\x18.yorkie.v1.DocWatchEventH\x00R\bdocEventB\a\n" +
	"\x05event\"[\n" +
	"\rDocWatchEvent\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12)\n" +
	"\x05event\x18\x02 \x01(\v2\x13.yorkie.v1.DocEventR\x05event\"T\n" +
	"\x14WatchDocumentRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\"\xd8\x01\n" +
	"\x15WatchDocumentResponse\x12Y\n" +
	"\x0einitialization\x18\x01 \x01(\v2/.yorkie.v1.WatchDocumentResponse.InitializationH\x00R\x0einitialization\x12+\n" +
	"\x05event\x18\x02 \x01(\v2\x13.yorkie.v1.DocEventH\x00R\x05event\x1a/\n" +
	"\x0eInitialization\x12\x1d\n" +
	"\n" +
	"client_ids\x18\x01 \x03(\tR\tclientIdsB\x06\n" +
	"\x04body\"\x8d\x01\n" +
	"\x15RemoveDocumentRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x126\n" +
	"\vchange_pack\x18\x03 \x01(\v2\x15.yorkie.v1.ChangePackR\n" +
	"changePack\"P\n" +
	"\x16RemoveDocumentResponse\x126\n" +
	"\vchange_pack\x18\x01 \x01(\v2\x15.yorkie.v1.ChangePackR\n" +
	"changePack\"\xab\x01\n" +
	"\x16PushPullChangesRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x126\n" +
	"\vchange_pack\x18\x03 \x01(\v2\x15.yorkie.v1.ChangePackR\n" +
	"changePack\x12\x1b\n" +
	"\tpush_only\x18\x04 \x01(\bR\bpushOnly\"Q\n" +
	"\x17PushPullChangesResponse\x126\n" +
	"\vchange_pack\x18\x01 \x01(\v2\x15.yorkie.v1.ChangePackR\n" +
	"changePack\"\x8d\x01\n" +
	"\x15CreateRevisionRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"P\n" +
	"\x16CreateRevisionResponse\x126\n" +
	"\brevision\x18\x01 \x01(\v2\x1a.yorkie.v1.RevisionSummaryR\brevision\"s\n" +
	"\x12GetRevisionRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1f\n" +
	"\vrevision_id\x18\x03 \x01(\tR\n" +
	"revisionId\"M\n" +
	"\x13GetRevisionResponse\x126\n" +
	"\brevision\x18\x01 \x01(\v2\x1a.yorkie.v1.RevisionSummaryR\brevision\"\xa8\x01\n" +
	"\x14ListRevisionsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x1d\n" +
	"\n" +
	"is_forward\x18\x05 \x01(\bR\tisForward\"Q\n" +
	"\x15ListRevisionsResponse\x128\n" +
	"\trevisions\x18\x01 \x03(\v2\x1a.yorkie.v1.RevisionSummaryR\trevisions\"w\n" +
	"\x16RestoreRevisionRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1f\n" +
	"\vrevision_id\x18\x04 \x01(\tR\n" +
	"revisionId\"\x19\n" +
	"\x17RestoreRevisionResponse\"T\n" +
	"\x14AttachChannelRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vchannel_key\x18\x02 \x01(\tR\n" +
	"channelKey\"[\n" +
	"\x15AttachChannelResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rsession_count\x18\x02 \x01(\x03R\fsessionCount\"s\n" +
	"\x14DetachChannelRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vchannel_key\x18\x02 \x01(\tR\n" +
	"channelKey\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"<\n" +
	"\x15DetachChannelResponse\x12#\n" +
	"\rsession_count\x18\x01 \x01(\x03R\fsessionCount\"t\n" +
	"\x15RefreshChannelRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vchannel_key\x18\x02 \x01(\tR\n" +
	"channelKey\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"=\n" +
	"\x16RefreshChannelResponse\x12#\n" +
	"\rsession_count\x18\x01 \x01(\x03R\fsessionCount\"\x80\x01\n" +
	"\x10BroadcastRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vchannel_key\x18\x02 \x01(\tR\n" +
	"channelKey\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\x13\n" +
	"\x11BroadcastResponse2\xf0\n" +
	"\n" +
	"\rYorkieService\x12W\n" +
	"\x0eActivateClient\x12 .yorkie.v1.ActivateClientRequest\x1a!.yorkie.v1.ActivateClientResponse\"\x00\x12]\n" +
	"\x10DeactivateClient\x12\".yorkie.v1.DeactivateClientRequest\x1a#.yorkie.v1.DeactivateClientResponse\"\x00\x12W\n" +
	"\x0eAttachDocument\x12 .yorkie.v1.AttachDocumentRequest\x1a!.yorkie.v1.AttachDocumentResponse\"\x00\x12W\n" +
	"\x0eDetachDocument\x12 .yorkie.v1.DetachDocumentRequest\x1a!.yorkie.v1.DetachDocumentResponse\"\x00\x12W\n" +
	"\x0eRemoveDocument\x12 .yorkie.v1.RemoveDocumentRequest\x1a!.yorkie.v1.RemoveDocumentResponse\"\x00\x12Z\n" +
	"\x0fPushPullChanges\x12!.yorkie.v1.PushPullChangesRequest\x1a\".yorkie.v1.PushPullChangesResponse\"\x00\x12>\n" +
	"\x05Watch\x12\x17.yorkie.v1.WatchRequest\x1a\x18.yorkie.v1.WatchResponse\"\x000\x01\x12V\n" +
	"\rWatchDocument\x12\x1f.yorkie.v1.WatchDocumentRequest\x1a .yorkie.v1.WatchDocumentResponse\"\x000\x01\x12W\n" +
	"\x0eCreateRevision\x12 .yorkie.v1.CreateRevisionRequest\x1a!.yorkie.v1.CreateRevisionResponse\"\x00\x12N\n" +
	"\vGetRevision\x12\x1d.yorkie.v1.GetRevisionRequest\x1a\x1e.yorkie.v1.GetRevisionResponse\"\x00\x12T\n" +
	"\rListRevisions\x12\x1f.yorkie.v1.ListRevisionsRequest\x1a .yorkie.v1.ListRevisionsResponse\"\x00\x12Z\n" +
	"\x0fRestoreRevision\x12!.yorkie.v1.RestoreRevisionRequest\x1a\".yorkie.v1.RestoreRevisionResponse\"\x00\x12T\n" +
	"\rAttachChannel\x12\x1f.yorkie.v1.AttachChannelRequest\x1a .yorkie.v1.AttachChannelResponse\"\x00\x12T\n" +
	"\rDetachChannel\x12\x1f.yorkie.v1.DetachChannelRequest\x1a .yorkie.v1.DetachChannelResponse\"\x00\x12W\n" +
	"\x0eRefreshChannel\x12 .yorkie.v1.RefreshChannelRequest\x1a!.yorkie.v1.RefreshChannelResponse\"\x00\x12H\n" +
	"\tBroadcast\x12\x1b.yorkie.v1.BroadcastRequest\x1a\x1c.yorkie.v1.BroadcastResponse\"\x00BE\n" +
	"\x11dev.yorkie.api.v1P\x01Z.github.com/yorkie-team/yorkie/api/yorkie/v1;v1b\x06proto3"

var (
	file_yorkie_v1_yorkie_proto_rawDescOnce sync.Once
	file_yorkie_v1_yorkie_proto_rawDescData []byte
)

func file_yorkie_v1_yorkie_proto_rawDescGZIP() []byte {
	file_yorkie_v1_yorkie_proto_rawDescOnce.Do(func() {
		file_yorkie_v1_yorkie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yorkie_v1_yorkie_proto_rawDesc), len(file_yorkie_v1_yorkie_proto_rawDesc)))
	})
	return file_yorkie_v1_yorkie_proto_rawDescData
}

var file_yorkie_v1_yorkie_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_yorkie_v1_yorkie_proto_goTypes = []any{
	(*ActivateClientRequest)(nil),                // 0: yorkie.v1.ActivateClientRequest
	(*ActivateClientResponse)(nil),               // 1: yorkie.v1.ActivateClientResponse
	(*DeactivateClientRequest)(nil),              // 2: yorkie.v1.DeactivateClientRequest
	(*DeactivateClientResponse)(nil),             // 3: yorkie.v1.DeactivateClientResponse
	(*AttachDocumentRequest)(nil),                // 4: yorkie.v1.AttachDocumentRequest
	(*AttachDocumentResponse)(nil),               // 5: yorkie.v1.AttachDocumentResponse
	(*DetachDocumentRequest)(nil),                // 6: yorkie.v1.DetachDocumentRequest
	(*DetachDocumentResponse)(nil),               // 7: yorkie.v1.DetachDocumentResponse
	(*WatchRequest)(nil),                         // 8: yorkie.v1.WatchRequest
	(*ResourceDescriptor)(nil),                   // 9: yorkie.v1.ResourceDescriptor
	(*DocumentDescriptor)(nil),                   // 10: yorkie.v1.DocumentDescriptor
	(*WatchResponse)(nil),                        // 11: yorkie.v1.WatchResponse
	(*WatchInitialization)(nil),                  // 12: yorkie.v1.WatchInitialization
	(*ResourceInit)(nil),                         // 13: yorkie.v1.ResourceInit
	(*DocumentInit)(nil),                         // 14: yorkie.v1.DocumentInit
	(*WatchEvent)(nil),                           // 15: yorkie.v1.WatchEvent
	(*DocWatchEvent)(nil),                        // 16: yorkie.v1.DocWatchEvent
	(*WatchDocumentRequest)(nil),                 // 17: yorkie.v1.WatchDocumentRequest
	(*WatchDocumentResponse)(nil),                // 18: yorkie.v1.WatchDocumentResponse
	(*RemoveDocumentRequest)(nil),                // 19: yorkie.v1.RemoveDocumentRequest
	(*RemoveDocumentResponse)(nil),               // 20: yorkie.v1.RemoveDocumentResponse
	(*PushPullChangesRequest)(nil),               // 21: yorkie.v1.PushPullChangesRequest
	(*PushPullChangesResponse)(nil),              // 22: yorkie.v1.PushPullChangesResponse
	(*CreateRevisionRequest)(nil),                // 23: yorkie.v1.CreateRevisionRequest
	(*CreateRevisionResponse)(nil),               // 24: yorkie.v1.CreateRevisionResponse
	(*GetRevisionRequest)(nil),                   // 25: yorkie.v1.GetRevisionRequest
	(*GetRevisionResponse)(nil),                  // 26: yorkie.v1.GetRevisionResponse
	(*ListRevisionsRequest)(nil),                 // 27: yorkie.v1.ListRevisionsRequest
	(*ListRevisionsResponse)(nil),                // 28: yorkie.v1.ListRevisionsResponse
	(*RestoreRevisionRequest)(nil),               // 29: yorkie.v1.RestoreRevisionRequest
	(*RestoreRevisionResponse)(nil),              // 30: yorkie.v1.RestoreRevisionResponse
	(*AttachChannelRequest)(nil),                 // 31: yorkie.v1.AttachChannelRequest
	(*AttachChannelResponse)(nil),                // 32: yorkie.v1.AttachChannelResponse
	(*DetachChannelRequest)(nil),                 // 33: yorkie.v1.DetachChannelRequest
	(*DetachChannelResponse)(nil),                // 34: yorkie.v1.DetachChannelResponse
	(*RefreshChannelRequest)(nil),                // 35: yorkie.v1.RefreshChannelRequest
	(*RefreshChannelResponse)(nil),               // 36: yorkie.v1.RefreshChannelResponse
	(*BroadcastRequest)(nil),                     // 37: yorkie.v1.BroadcastRequest
	(*BroadcastResponse)(nil),                    // 38: yorkie.v1.BroadcastResponse
	nil,                                          // 39: yorkie.v1.ActivateClientRequest.MetadataEntry
	(*WatchDocumentResponse_Initialization)(nil), // 40: yorkie.v1.WatchDocumentResponse.Initialization
	(*ChangePack)(nil),                           // 41: yorkie.v1.ChangePack
	(*Rule)(nil),                                 // 42: yorkie.v1.Rule
	(*DocEvent)(nil),                             // 43: yorkie.v1.DocEvent
	(*RevisionSummary)(nil),                      // 44: yorkie.v1.RevisionSummary
}
var file_yorkie_v1_yorkie_proto_depIdxs = []int32{
	39, // 0: yorkie.v1.ActivateClientRequest.metadata:type_name -> yorkie.v1.ActivateClientRequest.MetadataEntry
	41, // 1: yorkie.v1.AttachDocumentRequest.change_pack:type_name -> yorkie.v1.ChangePack
	41, // 2: yorkie.v1.AttachDocumentResponse.change_pack:type_name -> yorkie.v1.ChangePack
	42, // 3: yorkie.v1.AttachDocumentResponse.schema_rules:type_name -> yorkie.v1.Rule
	41, // 4: yorkie.v1.DetachDocumentRequest.change_pack:type_name -> yorkie.v1.ChangePack
	41, // 5: yorkie.v1.DetachDocumentResponse.change_pack:type_name -> yorkie.v1.ChangePack
	9,  // 6: yorkie.v1.WatchRequest.resources:type_name -> yorkie.v1.ResourceDescriptor
	10, // 7: yorkie.v1.ResourceDescriptor.document:type_name -> yorkie.v1.DocumentDescriptor
	12, // 8: yorkie.v1.WatchResponse.initialization:type_name -> yorkie.v1.WatchInitialization
	15, // 9: yorkie.v1.WatchResponse.event:type_name -> yorkie.v1.WatchEvent
	13, // 10: yorkie.v1.WatchInitialization.resource_inits:type_name -> yorkie.v1.ResourceInit
	14, // 11: yorkie.v1.ResourceInit.document_init:type_name -> yorkie.v1.DocumentInit
	16, // 12: yorkie.v1.WatchEvent.doc_event:type_name -> yorkie.v1.DocWatchEvent
	43, // 13: yorkie.v1.DocWatchEvent.event:type_name -> yorkie.v1.DocEvent
	40, // 14: yorkie.v1.WatchDocumentResponse.initialization:type_name -> yorkie.v1.WatchDocumentResponse.Initialization
	43, // 15: yorkie.v1.WatchDocumentResponse.event:type_name -> yorkie.v1.DocEvent
	41, // 16: yorkie.v1.RemoveDocumentRequest.change_pack:type_name -> yorkie.v1.ChangePack
	41, // 17: yorkie.v1.RemoveDocumentResponse.change_pack:type_name -> yorkie.v1.ChangePack
	41, // 18: yorkie.v1.PushPullChangesRequest.change_pack:type_name -> yorkie.v1.ChangePack
	41, // 19: yorkie.v1.PushPullChangesResponse.change_pack:type_name -> yorkie.v1.ChangePack
	44, // 20: yorkie.v1.CreateRevisionResponse.revision:type_name -> yorkie.v1.RevisionSummary
	44, // 21: yorkie.v1.GetRevisionResponse.revision:type_name -> yorkie.v1.RevisionSummary
	44, // 22: yorkie.v1.ListRevisionsResponse.revisions:type_name -> yorkie.v1.RevisionSummary
	0,  // 23: yorkie.v1.YorkieService.ActivateClient:input_type -> yorkie.v1.ActivateClientRequest
	2,  // 24: yorkie.v1.YorkieService.DeactivateClient:input_type -> yorkie.v1.DeactivateClientRequest
	4,  // 25: yorkie.v1.YorkieService.AttachDocument:input_type -> yorkie.v1.AttachDocumentRequest
	6,  // 26: yorkie.v1.YorkieService.DetachDocument:input_type -> yorkie.v1.DetachDocumentRequest
	19, // 27: yorkie.v1.YorkieService.RemoveDocument:input_type -> yorkie.v1.RemoveDocumentRequest
	21, // 28: yorkie.v1.YorkieService.PushPullChanges:input_type -> yorkie.v1.PushPullChangesRequest
	8,  // 29: yorkie.v1.YorkieService.Watch:input_type -> yorkie.v1.WatchRequest
	17, // 30: yorkie.v1.YorkieService.WatchDocument:input_type -> yorkie.v1.WatchDocumentRequest
	23, // 31: yorkie.v1.YorkieService.CreateRevision:input_type -> yorkie.v1.CreateRevisionRequest
	25, // 32: yorkie.v1.YorkieService.GetRevision:input_type -> yorkie.v1.GetRevisionRequest
	27, // 33: yorkie.v1.YorkieService.ListRevisions:input_type -> yorkie.v1.ListRevisionsRequest
	29, // 34: yorkie.v1.YorkieService.RestoreRevision:input_type -> yorkie.v1.RestoreRevisionRequest
	31, // 35: yorkie.v1.YorkieService.AttachChannel:input_type -> yorkie.v1.AttachChannelRequest
	33, // 36: yorkie.v1.YorkieService.DetachChannel:input_type -> yorkie.v1.DetachChannelRequest
	35, // 37: yorkie.v1.YorkieService.RefreshChannel:input_type -> yorkie.v1.RefreshChannelRequest
	37, // 38: yorkie.v1.YorkieService.Broadcast:input_type -> yorkie.v1.BroadcastRequest
	1,  // 39: yorkie.v1.YorkieService.ActivateClient:output_type -> yorkie.v1.ActivateClientResponse
	3,  // 40: yorkie.v1.YorkieService.DeactivateClient:output_type -> yorkie.v1.DeactivateClientResponse
	5,  // 41: yorkie.v1.YorkieService.AttachDocument:output_type -> yorkie.v1.AttachDocumentResponse
	7,  // 42: yorkie.v1.YorkieService.DetachDocument:output_type -> yorkie.v1.DetachDocumentResponse
	20, // 43: yorkie.v1.YorkieService.RemoveDocument:output_type -> yorkie.v1.RemoveDocumentResponse
	22, // 44: yorkie.v1.YorkieService.PushPullChanges:output_type -> yorkie.v1.PushPullChangesResponse
	11, // 45: yorkie.v1.YorkieService.Watch:output_type -> yorkie.v1.WatchResponse
	18, // 46: yorkie.v1.YorkieService.WatchDocument:output_type -> yorkie.v1.WatchDocumentResponse
	24, // 47: yorkie.v1.YorkieService.CreateRevision:output_type -> yorkie.v1.CreateRevisionResponse
	26, // 48: yorkie.v1.YorkieService.GetRevision:output_type -> yorkie.v1.GetRevisionResponse
	28, // 49: yorkie.v1.YorkieService.ListRevisions:output_type -> yorkie.v1.ListRevisionsResponse
	30, // 50: yorkie.v1.YorkieService.RestoreRevision:output_type -> yorkie.v1.RestoreRevisionResponse
	32, // 51: yorkie.v1.YorkieService.AttachChannel:output_type -> yorkie.v1.AttachChannelResponse
	34, // 52: yorkie.v1.YorkieService.DetachChannel:output_type -> yorkie.v1.DetachChannelResponse
	36, // 53: yorkie.v1.YorkieService.RefreshChannel:output_type -> yorkie.v1.RefreshChannelResponse
	38, // 54: yorkie.v1.YorkieService.Broadcast:output_type -> yorkie.v1.BroadcastResponse
	39, // [39:55] is the sub-list for method output_type
	23, // [23:39] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_yorkie_v1_yorkie_proto_init() }
func file_yorkie_v1_yorkie_proto_init() {
	if File_yorkie_v1_yorkie_proto != nil {
		return
	}
	file_yorkie_v1_resources_proto_init()
	file_yorkie_v1_yorkie_proto_msgTypes[9].OneofWrappers = []any{
		(*ResourceDescriptor_Document)(nil),
	}
	file_yorkie_v1_yorkie_proto_msgTypes[11].OneofWrappers = []any{
		(*WatchResponse_Initialization)(nil),
		(*WatchResponse_Event)(nil),
	}
	file_yorkie_v1_yorkie_proto_msgTypes[13].OneofWrappers = []any{
		(*ResourceInit_DocumentInit)(nil),
	}
	file_yorkie_v1_yorkie_proto_msgTypes[15].OneofWrappers = []any{
		(*WatchEvent_DocEvent)(nil),
	}
	file_yorkie_v1_yorkie_proto_msgTypes[18].OneofWrappers = []any{
		(*WatchDocumentResponse_Initialization_)(nil),
		(*WatchDocumentResponse_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yorkie_v1_yorkie_proto_rawDesc), len(file_yorkie_v1_yorkie_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yorkie_v1_yorkie_proto_goTypes,
		DependencyIndexes: file_yorkie_v1_yorkie_proto_depIdxs,
		MessageInfos:      file_yorkie_v1_yorkie_proto_msgTypes,
	}.Build()
	File_yorkie_v1_yorkie_proto = out.File
	file_yorkie_v1_yorkie_proto_goTypes = nil
	file_yorkie_v1_yorkie_proto_depIdxs = nil
}
